#!/usr/bin/env sh

# Exit on any error
set -e

echo '🏗️👷 Styling, testing and building your project before committing'

# Check Prettier
yarn check-format || (
  echo '🤢🤮 Prettier Check Failed. Run npm run format. 🤢🤮'
  exit 1
)

# Check ESLint
yarn check-lint || (
  echo '😤🏀 ESLint Check Failed. Fix the weak shit! 😤🏀'
  exit 1
)

# Check Types
yarn check-types || (
  echo '🤡😂 Failed Type check. 🤡😂'
  exit 1
)

# Build
yarn build || (
  echo '🤡🤡 Failed to build. 🤡🤡'
  exit 1
)

echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'
